### ISSUE TITLE
An error that would be supressed if I had my debug set to false

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-swift_mailer#5]
Reminder: I do have my $g_debug variable set to true so that's the only reason I even know this is occurring, but I figured I would make sure you were aware of it.
The error is only for HTML templates in emails. - the error doesn't occur in Text templates.

Notice: Undefined index: is_file_type in /var/www/subdomain.domain.com/vendor/smarty/smarty/libs/sysplugins/smarty_resource_recompiled.php(52) : eval()'d code on line 65

**Comment by benkeen** [comment]
Thanks @johnbleck3! Turns out this is in the core's email templates. I'll include a fix for this in the next Core release.

**Comment by benkeen** [comment]
Just FYI, this has been patched. The "is_file_type" in the HTML admin/client smarty loop email template should have been "is_file_field" - just a minor mistake on my part. To fix it in your own installation, just change that string in your email template. When you upgrade to 3.0.1 (coming soon) the prefab email templates from the dropdown will have been fixed, but not your existing email content that you've already created. 

Hope this is clear.
